# Shamelessly stolen from https://cclettenberg.com/ruby-on-rails/2015/05/28/jekyll-travis-ci-nearlyfreespeech.html
language: ruby
cache: bundle
#cache: bundler
script: 'rm -rf ./_site && bundle exec jekyll build && bundle exec htmlproofer ./_site --disable-external'
branches:
  #any branches you'd like Travis CI to test.
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

## before installing app
## Turn off strict host checking
## unzip encrypted ssh private key and _config.yml
before_install:
    - echo -e "Host ssh.phx.nearlyfreespeech.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - openssl aes-256-cbc -K $encrypted_ccfb71d23f49_key -iv $encrypted_ccfb71d23f49_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - bundle update

after_success:
    - chmod 600 .travis/ssh_key
    - eval "$(ssh-agent -s)"
    - ssh-add .travis/ssh_key
    - rake deploy

sudo: false # route your build to the container-based infrastructure for a faster build
